exports.PATH = 'bongvip'
exports.DATA = this.PATH + '/data'
exports.USERFILE = this.DATA + '/user.json'
exports.QUAYTHUONG = this.DATA + '/nhanlixi.json'
exports.DANHSACH = this.DATA + '/danhsach.json'